USE argenyx;
CREATE TABLE `argenyx`.`genes` (
	`Uploaded_variation` VARCHAR(300) NOT NULL ,
	`Location` VARCHAR(300) NOT NULL ,
	`Allele` VARCHAR(300) NOT NULL ,
       	`Consequence` VARCHAR(300) NOT NULL ,
	`IMPACT` VARCHAR(300) NOT NULL ,
	`SYMBOL` VARCHAR(300) NOT NULL ,
	`HGVSc` VARCHAR(300) NOT NULL ,
	`HGVSp` VARCHAR(300) NOT NULL ,
	`SIFT` VARCHAR(300) NOT NULL ,
	`PolyPhen` VARCHAR(300) NOT NULL ,
	`AF` VARCHAR(300) NOT NULL ,
	`gnomAD_AF` VARCHAR(300) NOT NULL ,
	`gnomAD_AFR_AF` VARCHAR(300) NOT NULL ,
	`gnomAD_AMR_AF` VARCHAR(300) NOT NULL ,
	`gnomAD_ASJ_AF` VARCHAR(300) NOT NULL ,
	`gnomAD_EAS_AF` VARCHAR(300) NOT NULL ,
	`gnomAD_FIN_AF` VARCHAR(300) NOT NULL ,
	`gnomAD_NFE_AF` VARCHAR(300) NOT NULL ,
	`gnomAD_OTH_AF` VARCHAR(300) NOT NULL ,
	`gnomAD_SAS_AF` VARCHAR(300) NOT NULL ,
	`CLIN_SIG` VARCHAR(300) NOT NULL 
) ENGINE = InnoDB;
